# `r fontawesome::fa("calendar-alt")` Schedule. {#sec-schedule}

`r fontawesome::fa("piggy-bank")` FCF1, Spring 2025. Online 10:00 a.m. – 11:30 a.m. Zoom [https://us02web.zoom.us/j/86461692747](https://us02web.zoom.us/j/86461692747)

## `r fontawesome::fa("battery-quarter")` Part 1.

**Session 1. `r fontawesome::fa("handshake")` Tuesday, January 14.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp account. Invitations have been sent to your UDEM student email.
- Activity. Define your team of no more than 4 members.
- Extra marks. Quiz 1. At 11:00 a.m., Quiz 1 will be available on Blackboard in the "Homeworks & exams" section. This is an in-class activity; you will have 25 minutes to complete it, and access to the quiz will close at 11:10 a.m. Quiz 1 consists of 10 true/false questions about the syllabus, with each question worth 0.5 points, allowing you to earn up to +5 extra points on your $E_1$ if answered correctly. With this activity, we will conclude the class.

**Session 2. Friday, January 17.**

- Reading. @drake2010basics, Chapter 1 *What is finance?*
- Reading. @brigham2009fundamentals, Chapter 1 *An overview of financial management*.
- Complementary material. Video 1/14: [Masters of Finance: Eugene Fama.](https://youtu.be/tRSaz5TIyno)
- Extra marks. Quiz 2. At 11:00 a.m., Quiz 2 will be available on Blackboard in the "Homeworks & exams" section. This is an in-class activity; you will have 25 minutes to complete it, and access to the quiz will close at 11:10 a.m. Quiz 2 consists of 10 true/false questions about the syllabus, with each question worth 0.5 points, allowing you to earn up to +5 extra points on your $E_1$ if answered correctly. With this activity, we will conclude the class. Quiz 1 and Quiz 2 are from the same question pool, so it is possible that you may encounter some repeated questions from Quiz 1.

**Session 3. Tuesday, January 21.**

- Reading. @drake2010basics, Chapter 1 *What is finance?*
- Reading. @brigham2009fundamentals, Chapter 1 *An overview of financial management*.
- Complementary material. Video 2/14: [Masters of Finance: Paul A. Samuelson.](https://youtu.be/RbIzwTGN3Yc)
- Extra marks. Quiz 3. At 11:00 a.m., Quiz 3 will be available on Blackboard in the "Homeworks & exams" section. This is an in-class activity, and you will have 25 minutes to complete it. Access to the quiz will close at 11:10 a.m. Quiz 3 consists of 10 true/false questions about the syllabus, at a higher level of difficulty compared to Quiz 1 and Quiz 2. Each question is worth 0.5 points, allowing you to earn up to +5 extra points on your $E_1$ if answered correctly. With this activity, we will conclude the class. 

**Session 4. Friday, January 24.**

- Reading. @brigham2009fundamentals, Chapter 2 *Financial markets and institutions*.
- Reading. @drake2010basics, Chapter 2 *Financial instruments, markets, and intermediaries*.
- Complementary material. Video 3/14: [Masters of Finance: Robert C. Merton.](https://youtu.be/cmzON43dWA4)

**Session 5. Tuesday, January 28.**

- Reading. @brigham2009fundamentals, Chapter 3 *Financial statements, cash flow, and taxes*.
- Reading. @drake2010basics, Chapter 4 *Financial statements*.

**Session 6. Friday, January 31.**

- Reading. @brigham2009fundamentals, Chapter 3 *Financial statements, cash flow, and taxes*.
- Reading. @drake2010basics, Chapter 4 *Financial statements*.
- Complementary material. Video 4/14: [Masters of Finance: Michael Jensen.](https://youtu.be/OWP6Hg2bvmo)
- Reading. Dinero e ideas. See: [https://mlozanoqf.github.io/ensayos/](https://mlozanoqf.github.io/ensayos/)

**Session 7. Tuesday, February 4.**

- Reading. @brigham2009fundamentals, Chapter 3 *Financial statements, cash flow, and taxes*.
- Reading. @drake2010basics, Chapter 4 *Financial statements*.
- Complementary material. [The Plastic Recycling Myth.](https://youtu.be/zZlRhCDzh2A)
- Complementary material. Video 5/14: [Masters of Finance: Myron Scholes.](https://youtu.be/zqfRmY1cag4)

**Session 8. Friday, February 7.**

- Guest lecturer.

**Session 9. Tuesday, February 11.**

- Guest lecturer.
- Activity. $H_1$ review.
- Complementary material. Video 6/14: [Masters of Finance: Ken Arrow.](https://youtu.be/A2lUzcr0S6M)
- Extra marks. DataCamp top 5 XP for the first 30 days. Wednesday, February 12.

**Session 10. `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")` Friday, February 14.**

- Graded. Complete $H_1$ before 10:00 a.m.
- Activity. $H_1$ presentations.

**Session 11. Tuesday, February 18.**

- Activity. $E_1$ review.
- Extra marks. Complete DataCamp assignments. It is not required to send evidence of having completed the tasks because the system automatically records if they were completed on time.
- Extra marks. Complete one UN CC:Learn course. Submit your PDF certificate before 10:00 a.m. by the discussion forum.

**Session 12. Friday, February 21.**

- Graded. $E_1$ Instructions in Blackboard.

## `r fontawesome::fa("battery-half")` Part 2.

**Session 13. Tuesday, February 25.**

- Activity. Discuss $E_1$ answers.
- Extra marks. The wheel of fortune 1/3. This is a class activity.
- Graded. Submit $H_1$ and $E_1$ co-evaluation before 10:00 a.m. Instructions in Blackboard.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 180 por favor.*

**Session 14. Friday, February 28.**

- Reading. @brigham2009fundamentals, Chapter 4 *Analysis of financial statements*.
- Reading. @drake2010basics, Chapter 11 *Financial ratio analysis*.

**Session 15. Tuesday, March 4.**

- Reading. @brigham2009fundamentals, Chapter 4 *Analysis of financial statements*.
- Reading. @drake2010basics, Chapter 11 *Financial ratio analysis*.
- Complementary material. Video 7/14: [Masters of Finance: Jack Treynor.](https://youtu.be/TdMf9nkKWhY)

**Session 16. `r fontawesome::fa("female")` Friday, March 7.**

- Reading. @brigham2009fundamentals, Chapter 4 *Analysis of financial statements*.
- Reading. @drake2010basics, Chapter 11 *Financial ratio analysis*.

**Session 17. Tuesday, March 11.**

- Guest lecturer.

**Session 18. $\pi$ Friday, March 14.**

- Guest lecturer.
- Extra marks. DataCamp top 5 XP for the days 31 to 60. Friday, March 14.

**Session 19. Tuesday, March 18.**

- Activity. $H_2$ review.
- Extra marks. Actividad +5 puntos sobe la calificación del segundo parcial. Compartir, reaccionar y/o agregar un comentario en redes sociales. Subir evidencia (screenshot) al foro de discusión del segundo parcial. La hora límite es 10:00 a.m. de la sesión 19: (1) *Retos y oportunidades en el aprendizaje de ciencia de datos en las escuelas de negocios.* [Spotify `r fontawesome::fa("spotify")`](https://open.spotify.com/episode/6x8c6XIPIfIPLj1yRhi5D8?si=bcee2af66ed54e09); [YouTube `r fontawesome::fa("youtube")`](https://youtu.be/SKG3Kr-TK-w?si=W5wg2DXluuiEspWC); [LinkedIn `r fontawesome::fa("linkedin")`](https://www.linkedin.com/posts/martin-lozano-21818a22_132-retos-y-oportunidades-en-el-aprendizaje-activity-7142212773349945344-1xHL?utm_source=share&utm_medium=member_desktop). Café de Datos, Datlas. Temporada 9, capítulo 132. Diciembre 2023. (2) *Riesgo financiero.* [Spotify `r fontawesome::fa("spotify")`](https://open.spotify.com/episode/7hrOh0tvDH3lioOfXtRqsT?si=8142007bc6ab4f56). Hablemos de economía y política. Asociación para la Conciencia Económica y Política (ACEyP). Noviembre 2024.

**Session 20. Friday, March 21.**

- Graded. Complete $H_2$ before 10:00 a.m.
- Activity. $H_2$ presentations.

**Session 21. Tuesday, March 25.**

- Activity. $E_2$ review.
- Extra marks. Complete DataCamp assignments. It is not required to send evidence of having completed the tasks because the system automatically records if they were completed on time.
- Extra marks. Complete one UN CC:Learn course. Submit your PDF certificate before 10:00 a.m. by the discussion forum.

**Session 22. Friday, March 28.**

- Graded. $E_2$ Instructions in Blackboard.

## `r fontawesome::fa("battery-three-quarters")` Part 3.

**Session 23. Tuesday, April 1.**

- Activity. Discuss $E_2$ answers.
- Extra marks. The wheel of fortune 2/3. This is a class activity.
- Graded. Submit $H_2$ and $E_2$ co-evaluation before 10:00 a.m. Instructions in Blackboard.

**Session 24. Friday, April 4.**

- Reading. @brigham2009fundamentals, Chapter 5 *Time value of money*.
- Reading. @drake2010basics, Chapter 10 *The math of finance*.
- Reading. Interés. See: [https://mlozanoqf.github.io/ensayos/](https://mlozanoqf.github.io/ensayos/)

**Session 25. Tuesday, April 8.**

- Reading. @brigham2009fundamentals, Chapter 5 *Time value of money*.
- Reading. @drake2010basics, Chapter 10 *The math of finance*.
- Complementary material. Video 8/14: [Masters of Finance: Richard Roll.](https://youtu.be/ma7W4Iqfctc)

**Session 26. Friday, April 11.**

- Reading. @brigham2009fundamentals, Chapter 5 *Time value of money*.
- Reading. @drake2010basics, Chapter 10 *The math of finance*.
- Complementary material. Video 9/14: [Masters of Finance: Harry Markowitz.](https://youtu.be/RVWEhCd819E)
- Extra marks. DataCamp top 5 XP for the days 61 to 90. Monday, April 14.

**Holiday. `r fontawesome::fa("umbrella-beach")` Tuesday, April 15.**

**Holiday. `r fontawesome::fa("umbrella-beach")` Friday, April 18.**

**Session 27. Tuesday, April 22.**

- Reading. @brigham2009fundamentals, Chapter 5 *Time value of money*.
- Reading. @drake2010basics, Chapter 10 *The math of finance*.
- Complementary material. Video 10/14: [Masters of Finance: William F. Sharpe.](https://youtu.be/PfVaOn9W3mo)
- Reading. Finanzas. See: [https://mlozanoqf.github.io/ensayos/](https://mlozanoqf.github.io/ensayos/)

**Session 28. Friday, April 25.**

- Reading. @brigham2009fundamentals, Chapter 6 *Interest rates*.
- Reading. @drake2010basics, Chapter 18 *The structure of interest rates*.

**Session 29. `r fontawesome::fa("children")` Tuesday, April 29.**

- Reading. @brigham2009fundamentals, Chapter 6 *Interest rates*.
- Reading. @drake2010basics, Chapter 18 *The structure of interest rates*.
- Complementary material. Video 11/14: [Masters of Finance: Robert Engle.](https://youtu.be/ejb1Ka2QqCw)

**Session 30. `r fontawesome::fa("jedi-order")` Friday, May 2.**

- Guest lecturer.
- Complementary material. Video 12/14: [Masters of Finance: Fred Weston.](https://youtu.be/12s9LUaYlE0)
- Reading. There is no free lunch. See: [https://mlozanoqf.github.io/ensayos/](https://mlozanoqf.github.io/ensayos/)

**Session 31. Tuesday, May 6.**

- Guest lecturer.
- Non graded. Mention DataCamp in social media if possible. [Instructions.](https://docs.google.com/document/d/1Dv-L036CZWsZCmn9W5p0ikgetlc4GcT-NQ9Rp_HebE0/edit)
- Complementary material. Video 13/14: [Masters of Finance: Maureen O'Hara.](https://youtu.be/vTB1ckSFA-w)
- Non-graded. Complete $H_3$ before 10:00 a.m.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 360 por favor.*

**Session 32. Friday, May 9.**

- Activity. $E_F$ review.
- Extra marks. Complete DataCamp assignments. It is not required to send evidence of having completed the tasks because the system automatically records if they were completed on time.
- Extra marks. Complete one UN CC:Learn course. Submit your PDF certificate before 10:00 a.m. by the discussion forum.
- Extra marks. The wheel of fortune 3/3. This is a class activity.
- Complementary material. Video 14/14: [Masters of Finance: Stephen Ross.](https://youtu.be/tKIwXnVEjWM)
- Farewell `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")`.

## `r fontawesome::fa("battery-full")` The end.

**Final exam, Zoom. Friday, May 23, 10:00 – 12:00.**

- Graded. $E_F$ Instructions in Blackboard.