

```{r include=FALSE}
rm(list = ls())
library(fontawesome)
library(vembedr)
library(tictoc)
tic()
```

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```


````{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('8 contact.html')
```
````

<!-- {{< fa thumbs-up >}}  -->
<!-- {{< fa folder >}} -->
<!-- {{< fa chess-pawn >}} -->
<!-- {{< fa brands bluetooth >}} -->
<!-- {{< fa brands twitter size=2xl >}} -->
<!-- {{< fa brands github size=5x >}} -->
<!-- {{< fa battery-half size=Huge >}} -->
<!-- {{< fa envelope title="An envelope" >}} -->

```{r introduction, child = '1 Well.Rmd'}
```


```{r overview, child = '2 Over.Rmd'}
```


```{r data science, child = '3 Data.Rmd'}
```


```{r resources and activities, child = '4 RA.Rmd'}
```


```{r evaluation, child = '5 Eva.Rmd'}
```


```{r check, child = '6 PoliCheck.Rmd'}
```


```{r schedule, child = 'Class schedule ot24.Rmd'}
```


```{r resources, child = '7 Int.Rmd'}
```

```{r include=FALSE}
a <- toc()
```


This document took `r round(as.numeric((a$toc-a$tic)), 2)` seconds to compile in Quarto version `r quarto::quarto_version()`, and `r R.version.string`.


# `r fontawesome::fa("book-open")` References. {.unnumbered}
::: {#refs}
:::
