---
title: Fundamentos Cuantitativos en Finanzas FCF. #`r fontawesome::fa("credit-card")`.
subtitle: Course syllabus. Fall 2023. 
author: Dr. Martín Lozano <tt>`<martin.lozano@udem.edu>`</tt>
#- name: Back to main [`r fontawesome::fa("home")`](https://mlozanoqf.github.io/)
#  affiliation: Academic website. [Web.](https://sites.google.com/site/mlozanoqf/)
date: Current `r fontawesome::fa("code-commit") ` `r format(Sys.time(), '%d %b %Y, %H:%M:%S.')` Under revision `r fontawesome::fa("exclamation-circle", fill = "red")`
#  bookdown::gitbook: default
output: 
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 2
    number_sections: yes
    fig_caption: yes
    code_folding: show
    theme: readable #darkly 
    includes:
      #after_body: analytics_arf1.html
abstract: A course syllabus is an academic document containing relevant information for students. This document serves as your ultimate guide to successfully completing this course. Please read it regularly and carefully. Within this document, you will find a comprehensive description of the course goals, rules, objectives, recommendations, grading details, a detailed schedule, activities, resources, references, and learning outcomes. The objective of this document is to provide you with complete certainty regarding what to expect from this course, starting from day 1 until the final exam. Based on my experience, reading this syllabus is positively correlated with students' performance.

#bibliography: mybibfile.bib
link-citations: true
---

```{=tex}
\newpage 
\hypersetup{linkcolor=black}
\renewcommand*\contentsname{Index.}
\tableofcontents
```

```{r include=FALSE}
# This removes all items in environment. 
# It is a good practice to start your code this way.
rm(list=ls())
library(fontawesome)
library(vembedr)
library(tictoc)
tic()
```

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```

```{r, xaringanExtra-clipboard, echo=FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clone fa-2x\" style=\"color: #301e64\"></i>",
    success_text = "<i class=\"fa fa-check fa-2x\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times fa-2x\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

````{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('contact.html')
```
````

# [`r fa("arrow-circle-up", fill = "black")`](https://mlozanoqf.github.io/ARF1/) [<span style="color: black">Back to top.</span>](https://mlozanoqf.github.io/ARF1/) {-}

\newpage



```{r include=FALSE}
a <- toc()
```

This document took `r round(as.numeric((a$toc-a$tic)), 2)` seconds to compile in Rmarkdown, `r R.version.string`.

# `r fontawesome::fa("book-open")` References.