
# `r fontawesome::fa("check-square")` Ensayos. {#sec-ensayos}

Considere las siguientes lecturas introductorias para comprender mejor los temas del curso.

## Dinero e ideas.

*Autor: Dr. Martín Lozano.*

Como en cualquier otra área de conocimiento, finanzas nos ayuda a comprender mejor el mundo complejo que nos rodea. Considere una simplificación radical en donde en este mundo cada uno de nosotros tiene dinero o ideas.  El dinero representa los recursos materiales, y las ideas son los recursos intelectuales. Tanto las ideas sin financiamiento, como el dinero por si mismos son improductivos. Pero las ideas con financiamiento tienen el potencial de generar más riqueza para los involucrados, y en el agregado crecimiento y desarrollo económico para la sociedad. Así, tenemos dos grupos de personas con intereses complementarios: las personas con dinero buscan oportunidades de inversión para incrementar su riqueza, y las personas con ideas buscan financiamiento para concretar sus proyectos.

En la práctica, las empresas compiten con otras para recibir recursos. Esta batalla es injusta porque frecuentemente es el tamaño de la empresa y no el potencial de la idea lo que atrae al financiamiento. Así, las empresas pequeñas terminan perdiendo, y la brecha entre las grandes y pequeñas aumenta. Por otro lado, si las opciones de financiamiento son escasas, entonces tenemos financiamiento costoso que dificulta que los proyectos tengan utilidades, las cuales son necesarias para que las personas con dinero reciban su compensación en forma de rendimiento. Si el sistema financiero es deficiente, entonces las buenas ideas pueden quedarse sin financiamiento o con uno muy caro, mientras que los malos proyectos podrían recibirlo en condiciones favorables. Por éstas y otras razones, las decisiones de inversión y financiamiento son complejas.

Incluso si el financiamiento no fuera un problema, todavía queda la posibilidad de que la idea fracase. Esto puede suceder por muchas razones, pero un factor que aglutina a la mayoría es el tiempo. El tiempo debe pasar para que una idea financiada genere los resultados esperados. Y como el tiempo es una fuente de incertidumbre, mientras los proyectos sean de más largo plazo, habrá más posibilidad de que algo salga mal y la idea fracase. Con lo cual, las decisiones de financiamiento e inversión no solo son complejas sino inciertas.

Por otro lado, uno de los principales retos de las decisiones de inversión es discernir entre las oportunidades disponibles. Esto es complejo porque necesitamos saber hoy el futuro y eso es claramente imposible. La alternativa es usar proyecciones sobre el posible desempeño de proyectos inciertos, para los cuales en ocasiones tenemos información limitada, incompleta o equivocada. Si se superan estas dificultades, y las proyecciones se estiman bien, el futuro se vuelve menos incierto al revelar qué tan bien y qué tan mal pueden ir las cosas para nuestros proyectos de inversión. Como resultado, podríamos ordenar las alternativas de inversión de acuerdo a su nivel de riesgo y asignar un mayor rendimiento esperado a aquellas alternativas con mayor riesgo. Así, si se superan estas dificultades y el análisis está libre de errores de estimación, discernir entre las oportunidades de inversión disponibles sería un poco menos incierto y eso significa que las decisiones se vuelvan un poco menos complejas.

Independientemente de que las decisiones de financiamiento e inversión sean complejas e inciertas, éstas se toman todos los días: desde contratar un plan de telefonía hasta financiar una vacuna. Tomar malas decisiones implica incurrir en costos adicionales, pérdida de empleos, recesiones o pérdida de vidas. Eso significa que los responsables de tomar estas decisiones deben ser profesionales con conocimiento del sistema financiero, la industria vinculada al proyecto, gestión de riesgos, econometría, evaluación de proyectos, estadística aplicada, ciencia de datos y posiblemente más áreas afines a finanzas. Todos los intentos y esfuerzos para mejorar nuestro entendimiento de las decisiones financieras, contribuye a mejorar las posibilidades de tener resultados prósperos para la sociedad.

Sería autocomplaciente decir que los financieros nos hemos distinguido por tomar buenas decisiones de inversión y financiamiento. Las diferencias entre los niveles de desarrollo económico, la pobreza, la falsa prosperidad a costa del medio ambiente, la mortalidad elevada de las empresas pequeñas, son consecuencia de saldos pendientes que finanzas tiene con la sociedad. No solo se requiere conocimiento, también es necesario que las personas involucradas se conduzcan con ética y no sucumban a la tentación de la corrupción.

Al final, en nuestro intento por comprender mejor el mundo en el que vivimos bajo la óptica de finanzas, podemos concluir que necesitamos a más personas buenas que tomen decisiones financieras de acuerdo al análisis de datos y con un criterio sostenible. Las decisiones financieras las tomamos todos y las consecuencias tienen el potencial de mejorar o empeorar nuestro nivel de vida. 


## Interés.

*Autor: Dr. Martín Lozano.*

El dinero, como cualquier otro bien escaso en la economía, tiene un valor. Se dice comúnmente que la tasa de interés es el precio del dinero, y como el dinero es lo que se requiere para comprar y vender bienes y servicios, la tasa de interés tiene el potencial de impactar a la actividad económica. De hecho, el dinero se puede comprar o vender gracias a que tiene precio. Por eso, cuando lo pido prestado, tengo que pagar un monto que se determina por la tasa de interés. O bien, cuando deposito mi dinero en el banco, recibo una cantidad equivalente a la tasa de interés. Entonces, la tasa de interés puede representar un costo o un ingreso monetario. En general, representa un costo cuando pido prestado, y es un ingreso cuando presto mi dinero. El tamaño del costo o ingreso monetario puede ser alto o bajo, eso depende de la tasa de interés.

No pedimos prestado dinero para contemplarlo sino para usarlo. Como pedir prestado implica un costo que tengo que pagar, entonces tengo que usarlo de manera inteligente para obtener un beneficio suficientemente alto y así estar en condiciones de pagarlo. Si el uso que le doy al dinero prestado resulta en una mala inversión, no voy a tener los recursos suficientes para pagar el préstamo y las consecuencias van desde una pérdida económica hasta recesiones económicas en un entorno más agregado. También debo ser cauteloso al prestarlo porque si cae en manos de personas irresponsables o que lo usan para financiar proyectos malos, es posible que no reciba mi pago correspondiente. El tamaño de estos incentivos para que el dinero se use de manera productiva y responsable, depende de la tasa de interés.

En economía también nos interesa otro tipo de costo que resulta más abstracto, pero al mismo tiempo muy real. El costo de oportunidad nos ayuda a comprender cómo tomamos las decisiones en la vida, incluyendo las decisiones financieras. Consideremos una situación en la que tengo una cantidad de dinero y dos posibles usos: irme de vacaciones de verano, o dejarlo en mi cuenta bancaria para recibir un ingreso igual a la tasa de interés. Si después de evaluarlo, decido ir de vacaciones, mi beneficio es mi diversión y mi costo de oportunidad es lo que hubiera recibido si lo hubiera dejado en el banco. Por otro lado, si decido mantenerlo en el banco, el beneficio es el ingreso que recibiré del banco y el costo de oportunidad es lo que me hubiera divertido en mis vacaciones. El costo de oportunidad representa lo que sacrifico al tomar una decisión. Con lo cual, si la tasa de interés es muy baja, seguramente iré de vacaciones porque no pierdo mucho. Sin embargo, si la tasa de interés es muy alta, seguramente pensaré dos veces si vale la pena irme de vacaciones. 

El nivel de la tasa de interés sube y baja a través del tiempo. Es verdad que puede tener periodos en donde se mantiene sin cambio, pero no es para siempre. Cuando la tasa de interés es alta, el costo de pedir prestado aumenta y el beneficio de dejarlo en el banco en forma de ahorro aumenta. Como consecuencia, las personas tendrán incentivos para reducir su nivel de consumo a crédito; y las empresas tendrán incentivos para reducir su nivel de inversión porque para ello se requiere pedir financiamiento o solicitar un crédito. Si las personas y empresas reducen sus niveles de consumo e inversión, entonces la actividad económica en general pierde dinamismo porque la demanda por bienes y servicios se reduce. Este resultado no parece muy atractivo porque en principio nadie desea que la actividad económica pierda dinamismo, pero aunque parezca paradójico en ocasiones esto es algo deseable. En particular, la reducción de la demanda agregada puede contribuir a reducir el precio de los bienes y servicios. Así, una tasa de interés elevada tiene el potencial de combatir la inflación elevada mediante desincentivar el consumo y la inversión.

Cuando la tasa de interés es baja, la lógica es parecida pero en sentido inverso. Esto es, el costo de pedir prestado se reduce y el beneficio de dejarlo en el banco en forma de ahorro disminuye. Como consecuencia, las personas y las empresas tendrán incentivos adicionales para consumir usando crédito e invertir solicitando financiamiento o préstamos bancarios. El aumento de la demanda agregada puede contribuir a estimular la actividad económica y eso parece ser una medida eficaz para salir de una recesión económica. Sin embargo, las decisiones de consumo e inversión no solo dependen de la tasa de interés, o del costo de financiamiento. Para invertir, las personas no solo necesitan dinero barato, sino también es necesario un determinado nivel de certeza sobre buenas perspectivas económicas para que sus inversiones tengan más probabilidad de ser exitosas. Con lo cual, podemos tener periodos en donde la tasa de interés es baja y la actividad económica se mantiene lenta, y eso se puede explicar por malas expectativas sobre el futuro.

En un entorno internacional, cuando un país X sube su tasa de interés, aumentan los incentivos de los extranjeros por depositar su dinero y aprovechar ese ingreso. Si esto sucede, el país X experimenta un incremento en la oferta de divisas extranjeras y una demanda por moneda local. El resultado tiende a ser un fortalecimiento de la moneda local. Esto es, más oferta de divisas extranjeras implica que las divisas extranjeras son menos escasas y por tanto más baratas en el país X. También lo podemos ver si pensamos en que la demanda por moneda local aumenta el precio de la moneda del país X. Una tasa de interés elevada puede explicar parte de la apreciación del tipo de cambio en el país X. Para completar este ejemplo, cuando un país X baja su tasa de interés, las divisas pueden salir y buscar otras alternativas de ahorro en otros países. Eso implica más escasez de divisas, lo cual significa divisas más caras, o una depreciación de la moneda local.

Hay muchas tasas de interés que conviven al mismo tiempo en la economía, pero en general tenemos una tasa de interés de referencia dictada por las autoridades monetarias del país. Una tasa de interés alta o baja no es buena o mala por si misma, su nivel debería cambiar en el tiempo para buscar mantener una estabilidad económica y financiera. Esta estabilidad es necesaria, aunque no suficiente, para que las decisiones financieras puedan tener mejores perspectivas y generen crecimiento económico sostenible y bienestar para las familias. Como su nombre lo sugiere, comprender la tasa de interés resulta interesante.

